export type WorkflowKey =
  | "lead"
  | "appointment"
  | "payment"
  | "document"
  | "support"
  | "education"
  | "healthcare"
  | "realEstate"
  | "hospitality"
  | "sales";

export type StateSeoSeed = {
  slug: string;
  name: string;
  cityClusters: string[];
  languages: string[];
  industries: string[];
  commercialAngle: string;
  primaryPain: string;
  workflows: WorkflowKey[];
  localSearchTerms: string[];
};

const publicServiceExamplesByWorkflow: Record<WorkflowKey, string[]> = {
  lead: ["WhatsApp enquiry handling", "website chat"],
  appointment: ["appointment booking"],
  payment: ["payment reminders"],
  document: ["document collection"],
  support: ["customer support workflows"],
  education: ["admission enquiry handling"],
  healthcare: ["patient intake and support"],
  realEstate: ["real estate lead follow-up"],
  hospitality: ["booking and guest follow-up"],
  sales: ["lead qualification and follow-up"],
};

export function getStatePublicServiceExamples(seed: StateSeoSeed) {
  return Array.from(new Set(seed.workflows.flatMap((workflow) => publicServiceExamplesByWorkflow[workflow] ?? [])));
}

export const stateSeoSeeds: Record<string, StateSeoSeed> = {
  maharashtra: {
    slug: "maharashtra",
    name: "Maharashtra",
    cityClusters: ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane"],
    languages: ["Marathi", "Hindi", "English"],
    industries: ["hospitals", "clinics", "real estate teams", "education institutes", "service businesses"],
    commercialAngle: "customer operations across metro, tier-1, and tier-2 business clusters",
    primaryPain: "missed WhatsApp leads, delayed follow-ups, manual booking coordination, payment reminders, and document collection",
    workflows: ["lead", "appointment", "payment", "document", "support", "healthcare", "realEstate"],
    localSearchTerms: ["whatsapp automation maharashtra", "whatsapp chatbot mumbai", "appointment automation pune"],
  },
  "uttar-pradesh": {
    slug: "uttar-pradesh",
    name: "Uttar Pradesh",
    cityClusters: ["Lucknow", "Noida", "Ghaziabad", "Kanpur", "Varanasi"],
    languages: ["Hindi", "English", "Urdu"],
    industries: ["healthcare providers", "schools", "coaching centres", "service businesses", "distributed sales teams"],
    commercialAngle: "busy customer operations across education, healthcare, local services, and regional sales networks",
    primaryPain: "high inquiry volume, missed callbacks, manual admission follow-ups, appointment chaos, and payment chasing",
    workflows: ["lead", "appointment", "education", "payment", "support", "document"],
    localSearchTerms: ["whatsapp automation uttar pradesh", "whatsapp chatbot noida", "school automation lucknow"],
  },
  "tamil-nadu": {
    slug: "tamil-nadu",
    name: "Tamil Nadu",
    cityClusters: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
    languages: ["Tamil", "English"],
    industries: ["hospitals", "education institutes", "manufacturing suppliers", "clinics", "service businesses"],
    commercialAngle: "healthcare, education, manufacturing, and local service needs across major business cities",
    primaryPain: "manual enquiry handling, delayed appointment booking, repetitive support replies, and missed follow-up opportunities",
    workflows: ["lead", "appointment", "healthcare", "education", "payment", "support"],
    localSearchTerms: ["whatsapp automation tamil nadu", "whatsapp chatbot chennai", "clinic automation coimbatore"],
  },
  "west-bengal": {
    slug: "west-bengal",
    name: "West Bengal",
    cityClusters: ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"],
    languages: ["Bengali", "Hindi", "English"],
    industries: ["healthcare providers", "diagnostic centres", "education institutes", "local services", "tourism businesses"],
    commercialAngle: "customer-service needs across healthcare, diagnostics, education, retail, and local services",
    primaryPain: "slow responses, report-status queries, appointment follow-ups, and repeated customer support questions",
    workflows: ["appointment", "healthcare", "document", "support", "education", "payment"],
    localSearchTerms: ["whatsapp automation west bengal", "whatsapp chatbot kolkata", "diagnostic automation kolkata"],
  },
  karnataka: {
    slug: "karnataka",
    name: "Karnataka",
    cityClusters: ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi"],
    languages: ["Kannada", "English", "Hindi"],
    industries: ["SaaS companies", "hospitals", "real estate teams", "education institutes", "service businesses"],
    commercialAngle: "digital-first business adoption across technology, healthcare, education, real estate, and services",
    primaryPain: "lead leakage, delayed sales follow-ups, appointment coordination, and fragmented customer conversations",
    workflows: ["lead", "sales", "appointment", "realEstate", "support", "payment"],
    localSearchTerms: ["whatsapp automation karnataka", "whatsapp chatbot bengaluru", "real estate automation bangalore"],
  },
  "madhya-pradesh": {
    slug: "madhya-pradesh",
    name: "Madhya Pradesh",
    cityClusters: ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"],
    languages: ["Hindi", "English"],
    industries: ["hospitals", "schools", "coaching centres", "real estate teams", "local service businesses"],
    commercialAngle: "fast-growing service demand across education, healthcare, real estate, and city-level business hubs",
    primaryPain: "manual enquiry management, missed admissions leads, delayed callbacks, and payment reminder gaps",
    workflows: ["lead", "education", "appointment", "payment", "support", "document"],
    localSearchTerms: ["whatsapp automation madhya pradesh", "whatsapp chatbot indore", "school automation bhopal"],
  },
  rajasthan: {
    slug: "rajasthan",
    name: "Rajasthan",
    cityClusters: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer"],
    languages: ["Hindi", "English", "Marwari"],
    industries: ["tourism businesses", "hotels", "hospitals", "coaching centres", "real estate teams"],
    commercialAngle: "strong demand across tourism, education, healthcare, hospitality, and property enquiries",
    primaryPain: "booking follow-ups, enquiry qualification, payment reminders, admission queries, and repetitive customer questions",
    workflows: ["hospitality", "lead", "education", "appointment", "payment", "support"],
    localSearchTerms: ["whatsapp automation rajasthan", "whatsapp chatbot jaipur", "hotel automation udaipur"],
  },
  gujarat: {
    slug: "gujarat",
    name: "Gujarat",
    cityClusters: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"],
    languages: ["Gujarati", "Hindi", "English"],
    industries: ["manufacturers", "exporters", "hospitals", "finance services", "service businesses"],
    commercialAngle: "business-heavy market with strong sales, service, manufacturing, export, and healthcare workflows",
    primaryPain: "manual lead qualification, sales follow-ups, payment tracking, document collection, and support escalations",
    workflows: ["lead", "sales", "payment", "document", "support", "healthcare"],
    localSearchTerms: ["whatsapp automation gujarat", "whatsapp chatbot ahmedabad", "sales automation surat"],
  },
  bihar: {
    slug: "bihar",
    name: "Bihar",
    cityClusters: ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga"],
    languages: ["Hindi", "English", "Bhojpuri", "Maithili"],
    industries: ["coaching centres", "schools", "clinics", "finance services", "local service businesses"],
    commercialAngle: "education, healthcare, finance, and local service businesses handling high inquiry volume",
    primaryPain: "manual admission follow-ups, fee reminders, missed enquiries, and slow support response",
    workflows: ["education", "lead", "payment", "appointment", "support", "document"],
    localSearchTerms: ["whatsapp automation bihar", "coaching centre automation patna", "school chatbot bihar"],
  },
  "andhra-pradesh": {
    slug: "andhra-pradesh",
    name: "Andhra Pradesh",
    cityClusters: ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Kurnool"],
    languages: ["Telugu", "English", "Hindi"],
    industries: ["hospitals", "education institutes", "real estate teams", "local services", "distribution businesses"],
    commercialAngle: "regional business growth across healthcare, education, property, distribution, and services",
    primaryPain: "manual booking coordination, enquiry tracking, payment reminders, and delayed follow-ups",
    workflows: ["lead", "appointment", "healthcare", "education", "payment", "support"],
    localSearchTerms: ["whatsapp automation andhra pradesh", "whatsapp chatbot vijayawada", "hospital automation visakhapatnam"],
  },
  telangana: {
    slug: "telangana",
    name: "Telangana",
    cityClusters: ["Hyderabad", "Warangal", "Karimnagar", "Nizamabad", "Khammam"],
    languages: ["Telugu", "English", "Hindi", "Urdu"],
    industries: ["hospitals", "SaaS teams", "real estate companies", "education institutes", "service businesses"],
    commercialAngle: "high digital adoption across Hyderabad-led business, healthcare, education, and property markets",
    primaryPain: "lead leakage, support overload, booking coordination, document collection, and payment follow-ups",
    workflows: ["lead", "sales", "appointment", "realEstate", "payment", "support"],
    localSearchTerms: ["whatsapp automation telangana", "whatsapp chatbot hyderabad", "real estate automation hyderabad"],
  },
  odisha: {
    slug: "odisha",
    name: "Odisha",
    cityClusters: ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Sambalpur"],
    languages: ["Odia", "English", "Hindi"],
    industries: ["hospitals", "education institutes", "industrial services", "tourism businesses", "local service businesses"],
    commercialAngle: "service-led demand across healthcare, education, tourism, industrial support, and city businesses",
    primaryPain: "slow enquiry response, appointment follow-up gaps, document collection, and repetitive customer support",
    workflows: ["lead", "appointment", "healthcare", "education", "document", "support"],
    localSearchTerms: ["whatsapp automation odisha", "whatsapp chatbot bhubaneswar", "clinic automation odisha"],
  },
  "jammu-and-kashmir": {
    slug: "jammu-and-kashmir",
    name: "Jammu and Kashmir",
    cityClusters: ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur"],
    languages: ["Urdu", "Hindi", "English", "Kashmiri"],
    industries: ["tourism businesses", "hotels", "clinics", "schools", "local service businesses"],
    commercialAngle: "tourism, healthcare, education, and local services need fast customer response across seasonal demand",
    primaryPain: "booking enquiries, travel follow-ups, appointment requests, and repetitive support questions",
    workflows: ["hospitality", "lead", "appointment", "support", "payment", "document"],
    localSearchTerms: ["whatsapp automation jammu and kashmir", "hotel chatbot srinagar", "clinic automation jammu"],
  },
  uttarakhand: {
    slug: "uttarakhand",
    name: "Uttarakhand",
    cityClusters: ["Dehradun", "Haridwar", "Rishikesh", "Haldwani", "Nainital"],
    languages: ["Hindi", "English"],
    industries: ["tourism businesses", "hotels", "schools", "clinics", "real estate teams"],
    commercialAngle: "tourism, education, healthcare, and property enquiries across seasonal and city-led demand",
    primaryPain: "booking follow-ups, admission enquiries, appointment coordination, and support overload",
    workflows: ["hospitality", "education", "appointment", "lead", "payment", "support"],
    localSearchTerms: ["whatsapp automation uttarakhand", "hotel automation rishikesh", "school chatbot dehradun"],
  },
  "himachal-pradesh": {
    slug: "himachal-pradesh",
    name: "Himachal Pradesh",
    cityClusters: ["Shimla", "Dharamshala", "Manali", "Solan", "Mandi"],
    languages: ["Hindi", "English"],
    industries: ["hotels", "tourism operators", "clinics", "schools", "local service businesses"],
    commercialAngle: "seasonal tourism and local services need fast enquiry handling, reminders, and booking support",
    primaryPain: "manual booking replies, missed tourism leads, slow callbacks, and repeated support questions",
    workflows: ["hospitality", "lead", "appointment", "support", "payment", "document"],
    localSearchTerms: ["whatsapp automation himachal pradesh", "hotel chatbot manali", "tourism automation shimla"],
  },
  tripura: {
    slug: "tripura",
    name: "Tripura",
    cityClusters: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"],
    languages: ["Bengali", "Kokborok", "English", "Hindi"],
    industries: ["education institutes", "clinics", "retail businesses", "local service businesses"],
    commercialAngle: "education, healthcare, retail, and services benefit from structured customer conversations",
    primaryPain: "missed enquiries, manual follow-ups, appointment requests, and payment reminder gaps",
    workflows: ["education", "lead", "appointment", "payment", "support"],
    localSearchTerms: ["whatsapp automation tripura", "whatsapp chatbot agartala", "clinic automation tripura"],
  },
  goa: {
    slug: "goa",
    name: "Goa",
    cityClusters: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
    languages: ["English", "Konkani", "Hindi"],
    industries: ["hotels", "tourism businesses", "real estate teams", "clinics", "service businesses"],
    commercialAngle: "hospitality, tourism, property, healthcare, and service businesses handling high-intent customer enquiries",
    primaryPain: "booking enquiries, property lead follow-ups, payment confirmations, and guest support questions",
    workflows: ["hospitality", "realEstate", "lead", "payment", "support", "appointment"],
    localSearchTerms: ["whatsapp automation goa", "hotel chatbot goa", "real estate automation goa"],
  },
  puducherry: {
    slug: "puducherry",
    name: "Puducherry",
    cityClusters: ["Puducherry", "Karaikal", "Yanam", "Mahe"],
    languages: ["Tamil", "English", "Telugu", "Malayalam"],
    industries: ["tourism businesses", "clinics", "education institutes", "local service businesses"],
    commercialAngle: "tourism, healthcare, education, and services benefit from faster WhatsApp-first communication",
    primaryPain: "manual booking replies, appointment requests, enquiry follow-ups, and repeated support messages",
    workflows: ["hospitality", "appointment", "lead", "education", "payment", "support"],
    localSearchTerms: ["whatsapp automation puducherry", "hotel chatbot puducherry", "clinic automation puducherry"],
  },
  chandigarh: {
    slug: "chandigarh",
    name: "Chandigarh",
    cityClusters: ["Chandigarh", "Mohali", "Panchkula", "Zirakpur"],
    languages: ["Hindi", "Punjabi", "English"],
    industries: ["clinics", "real estate teams", "education institutes", "finance consultants", "service businesses"],
    commercialAngle: "premium service businesses need polished automation for leads, appointments, reminders, and support",
    primaryPain: "missed premium leads, delayed callbacks, manual appointment handling, and document follow-ups",
    workflows: ["lead", "appointment", "realEstate", "document", "payment", "support"],
    localSearchTerms: ["whatsapp automation chandigarh", "clinic chatbot chandigarh", "real estate automation chandigarh"],
  },
  manipur: {
    slug: "manipur",
    name: "Manipur",
    cityClusters: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
    languages: ["Meiteilon", "English", "Hindi"],
    industries: ["education institutes", "clinics", "retail businesses", "local service businesses"],
    commercialAngle: "local businesses can reduce manual customer handling through structured chat workflows",
    primaryPain: "missed enquiries, slow support replies, appointment coordination, and manual follow-ups",
    workflows: ["education", "lead", "appointment", "support", "payment"],
    localSearchTerms: ["whatsapp automation manipur", "whatsapp chatbot imphal", "clinic automation manipur"],
  },
  nagaland: {
    slug: "nagaland",
    name: "Nagaland",
    cityClusters: ["Kohima", "Dimapur", "Mokokchung", "Wokha"],
    languages: ["English", "Nagamese", "Hindi"],
    industries: ["education institutes", "clinics", "retail businesses", "local service businesses"],
    commercialAngle: "service teams can use WhatsApp automation to respond faster and reduce manual work",
    primaryPain: "manual enquiries, delayed callbacks, repetitive questions, and payment follow-ups",
    workflows: ["lead", "education", "appointment", "payment", "support"],
    localSearchTerms: ["whatsapp automation nagaland", "whatsapp chatbot dimapur", "clinic automation nagaland"],
  },
  meghalaya: {
    slug: "meghalaya",
    name: "Meghalaya",
    cityClusters: ["Shillong", "Tura", "Jowai", "Nongpoh"],
    languages: ["English", "Khasi", "Garo", "Hindi"],
    industries: ["tourism businesses", "education institutes", "clinics", "local service businesses"],
    commercialAngle: "tourism, education, healthcare, and local services need quick response and clean follow-up systems",
    primaryPain: "booking queries, missed leads, appointment requests, and repetitive customer support messages",
    workflows: ["hospitality", "education", "appointment", "lead", "support", "payment"],
    localSearchTerms: ["whatsapp automation meghalaya", "hotel chatbot shillong", "clinic automation meghalaya"],
  },
  mizoram: {
    slug: "mizoram",
    name: "Mizoram",
    cityClusters: ["Aizawl", "Lunglei", "Champhai", "Serchhip"],
    languages: ["Mizo", "English", "Hindi"],
    industries: ["education institutes", "clinics", "retail businesses", "local service businesses"],
    commercialAngle: "customer-facing teams can automate enquiries, reminders, bookings, and support from one workflow",
    primaryPain: "manual enquiry tracking, missed callbacks, appointment handling, and repetitive status questions",
    workflows: ["education", "lead", "appointment", "support", "payment"],
    localSearchTerms: ["whatsapp automation mizoram", "whatsapp chatbot aizawl", "clinic automation mizoram"],
  },
  "arunachal-pradesh": {
    slug: "arunachal-pradesh",
    name: "Arunachal Pradesh",
    cityClusters: ["Itanagar", "Naharlagun", "Pasighat", "Tawang"],
    languages: ["English", "Hindi"],
    industries: ["tourism businesses", "education institutes", "clinics", "local service businesses"],
    commercialAngle: "tourism, education, healthcare, and service teams need simple automation for enquiries and follow-ups",
    primaryPain: "slow response to enquiries, manual booking coordination, appointment requests, and payment reminders",
    workflows: ["hospitality", "education", "appointment", "lead", "support"],
    localSearchTerms: ["whatsapp automation arunachal pradesh", "tourism chatbot arunachal", "clinic automation itanagar"],
  },
  sikkim: {
    slug: "sikkim",
    name: "Sikkim",
    cityClusters: ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
    languages: ["Nepali", "English", "Hindi"],
    industries: ["tourism businesses", "hotels", "clinics", "education institutes", "local services"],
    commercialAngle: "tourism and service-led businesses can convert more enquiries with fast WhatsApp-first follow-up",
    primaryPain: "missed booking enquiries, repetitive support questions, appointment requests, and delayed confirmations",
    workflows: ["hospitality", "lead", "appointment", "payment", "support"],
    localSearchTerms: ["whatsapp automation sikkim", "hotel chatbot gangtok", "tourism automation sikkim"],
  },
  "andaman-and-nicobar-islands": {
    slug: "andaman-and-nicobar-islands",
    name: "Andaman and Nicobar Islands",
    cityClusters: ["Port Blair", "Havelock", "Neil Island", "Mayabunder"],
    languages: ["Hindi", "English", "Bengali", "Tamil"],
    industries: ["tourism businesses", "hotels", "travel operators", "clinics", "local service businesses"],
    commercialAngle: "tourism-led businesses can automate bookings, enquiries, payment confirmations, and guest support",
    primaryPain: "manual travel enquiries, delayed booking replies, payment confirmation gaps, and repeated guest questions",
    workflows: ["hospitality", "lead", "payment", "support", "appointment"],
    localSearchTerms: ["whatsapp automation andaman", "hotel chatbot port blair", "travel automation andaman"],
  },
  ladakh: {
    slug: "ladakh",
    name: "Ladakh",
    cityClusters: ["Leh", "Kargil", "Nubra", "Zanskar"],
    languages: ["Ladakhi", "Hindi", "English"],
    industries: ["tourism businesses", "hotels", "travel operators", "clinics", "local service businesses"],
    commercialAngle: "seasonal tourism and local services need fast enquiry handling and reliable follow-up automation",
    primaryPain: "booking overload during peak season, missed enquiries, payment follow-ups, and repeated travel questions",
    workflows: ["hospitality", "lead", "payment", "support", "appointment"],
    localSearchTerms: ["whatsapp automation ladakh", "hotel chatbot leh", "travel automation ladakh"],
  },
  "dadra-and-nagar-haveli-and-daman-and-diu": {
    slug: "dadra-and-nagar-haveli-and-daman-and-diu",
    name: "Dadra and Nagar Haveli and Daman and Diu",
    cityClusters: ["Silvassa", "Daman", "Diu"],
    languages: ["Gujarati", "Hindi", "English"],
    industries: ["manufacturing units", "logistics teams", "tourism businesses", "clinics", "local service businesses"],
    commercialAngle: "manufacturing, logistics, tourism, and service businesses need faster enquiry and document workflows",
    primaryPain: "manual lead routing, document collection, payment follow-ups, and repeated support queries",
    workflows: ["lead", "document", "sales", "payment", "support", "hospitality"],
    localSearchTerms: ["whatsapp automation daman", "whatsapp chatbot silvassa", "business automation daman diu"],
  },
  lakshadweep: {
    slug: "lakshadweep",
    name: "Lakshadweep",
    cityClusters: ["Kavaratti", "Agatti", "Minicoy", "Amini"],
    languages: ["Malayalam", "English", "Hindi"],
    industries: ["tourism businesses", "hospitality teams", "local services", "healthcare providers"],
    commercialAngle: "tourism and service businesses can manage enquiries, confirmations, and customer updates more reliably",
    primaryPain: "manual booking responses, delayed confirmations, payment follow-ups, and repetitive guest questions",
    workflows: ["hospitality", "lead", "payment", "support", "appointment"],
    localSearchTerms: ["whatsapp automation lakshadweep", "hotel chatbot lakshadweep", "travel automation lakshadweep"],
  },
  assam: {
    slug: "assam",
    name: "Assam",
    cityClusters: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"],
    languages: ["Assamese", "English", "Hindi"],
    industries: ["hospitals", "education institutes", "retail businesses", "tourism businesses", "local service businesses"],
    commercialAngle: "regional customer demand across healthcare, education, tourism, retail, and local services",
    primaryPain: "missed enquiries, delayed follow-ups, appointment coordination, payment reminders, and repetitive support work",
    workflows: ["lead", "appointment", "payment", "support", "education"],
    localSearchTerms: ["whatsapp automation assam", "whatsapp chatbot guwahati", "business automation assam"],
  },
  chhattisgarh: {
    slug: "chhattisgarh",
    name: "Chhattisgarh",
    cityClusters: ["Raipur", "Bhilai Nagar", "Korba", "Bilaspur", "Durg"],
    languages: ["Hindi", "English"],
    industries: ["hospitals", "education institutes", "industrial services", "finance services", "local service businesses"],
    commercialAngle: "growing city-level demand across healthcare, education, industrial support, and services",
    primaryPain: "manual enquiry handling, delayed callbacks, payment reminders, booking coordination, and support overload",
    workflows: ["lead", "appointment", "payment", "support", "document"],
    localSearchTerms: ["whatsapp automation chhattisgarh", "whatsapp chatbot raipur", "business automation chhattisgarh"],
  },
  haryana: {
    slug: "haryana",
    name: "Haryana",
    cityClusters: ["Faridabad", "Gurugram", "Rohtak", "Hisar", "Panipat"],
    languages: ["Hindi", "English", "Punjabi"],
    industries: ["real estate teams", "hospitals", "education institutes", "distributed sales teams", "service businesses"],
    commercialAngle: "NCR-linked lead, sales, healthcare, and service demand across fast-moving urban clusters",
    primaryPain: "lead leakage, missed callbacks, manual booking coordination, payment follow-ups, and fragmented support conversations",
    workflows: ["lead", "sales", "appointment", "payment", "support"],
    localSearchTerms: ["whatsapp automation haryana", "whatsapp chatbot gurugram", "lead automation haryana"],
  },
  jharkhand: {
    slug: "jharkhand",
    name: "Jharkhand",
    cityClusters: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro Steel City", "Mango"],
    languages: ["Hindi", "English"],
    industries: ["hospitals", "education institutes", "industrial services", "finance services", "local service businesses"],
    commercialAngle: "city-led demand across healthcare, industrial support, education, and local service operations",
    primaryPain: "slow enquiry response, missed follow-ups, appointment handling gaps, payment reminders, and repetitive support work",
    workflows: ["lead", "appointment", "payment", "support", "document"],
    localSearchTerms: ["whatsapp automation jharkhand", "whatsapp chatbot ranchi", "business automation jharkhand"],
  },
  kerala: {
    slug: "kerala",
    name: "Kerala",
    cityClusters: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur"],
    languages: ["Malayalam", "English", "Hindi"],
    industries: ["hospitals", "tourism businesses", "education institutes", "clinics", "service businesses"],
    commercialAngle: "strong healthcare, tourism, education, and service demand across high-response customer journeys",
    primaryPain: "manual booking coordination, missed follow-ups, payment reminders, appointment gaps, and repeated support queries",
    workflows: ["hospitality", "appointment", "healthcare", "payment", "support"],
    localSearchTerms: ["whatsapp automation kerala", "whatsapp chatbot kochi", "hospital automation kerala"],
  },
  punjab: {
    slug: "punjab",
    name: "Punjab",
    cityClusters: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda"],
    languages: ["Punjabi", "Hindi", "English"],
    industries: ["hospitals", "education institutes", "real estate teams", "finance consultants", "service businesses"],
    commercialAngle: "strong city demand across healthcare, education, property, finance, and services",
    primaryPain: "missed premium leads, delayed callbacks, booking follow-up gaps, payment chasing, and repetitive support work",
    workflows: ["lead", "appointment", "payment", "support", "document"],
    localSearchTerms: ["whatsapp automation punjab", "whatsapp chatbot ludhiana", "business automation punjab"],
  },
  delhi: {
    slug: "delhi",
    name: "Delhi",
    cityClusters: ["Delhi", "New Delhi", "Nangloi", "Sultan Pur Majra", "Deoli"],
    languages: ["Hindi", "English", "Punjabi"],
    industries: ["hospitals", "real estate teams", "education institutes", "support teams", "service businesses"],
    commercialAngle: "high-intent customer operations across healthcare, property, education, support, and urban service demand",
    primaryPain: "lead leakage, delayed callbacks, appointment overload, payment reminders, and fragmented support conversations",
    workflows: ["lead", "sales", "appointment", "payment", "support", "document"],
    localSearchTerms: ["whatsapp automation delhi", "whatsapp chatbot delhi", "business automation delhi"],
  },
};

export const stateSeoSeedList = Object.values(stateSeoSeeds);
export const stateSeoSeedBySlug = new Map(stateSeoSeedList.map((seed) => [seed.slug, seed] as const));
